language: python
python:
  - "2.7"
  - "3.4"
cache: pip
sudo: false
env:
  matrix:
    - TOX_ENV=py27-dj17
    - TOX_ENV=py27-dj18
    - TOX_ENV=py34-dj17
    - TOX_ENV=py34-dj18
install:
  - pip install --upgrade pip
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV coverage
after_success:
  - coveralls
after_script:
  - cat .tox/$TOX_ENV/log/*.log
