language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"
env:
  - DJANGO_PACKAGE=Django==1.3.7
  - DJANGO_PACKAGE=Django==1.4.5
  - DJANGO_PACKAGE=Django==1.5.1
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - python setup.py install
matrix:
  allow_failures:
    - python:
      - "3.2"
      - "3.3"
script: make test
